config/routes.rb
Rails.application.routes.draw do
  get '/markers/self' => "markers#self"
  resources :markers
  get '/markers/:id/up' => "markers#upvote"
  get '/markers/:id/down' => "markers#downvote"
  get '/markers/:id/verify' => "markers#verify"
  get '/markers/:id/resolve' => "markers#resolve"
  

  root to: 'homes#index'
  get "homes" => "homes#index"
  get "user" => "homes#user"
  get "authority" => "homes#authority"
  get "login" => "homes#login"

  get    '/users/login'   => 'sessions#new'
  post   '/users/login'   => 'sessions#create'
  delete '/users/sign_out'  => 'sessions#destroy'
  get "setLocation" => 'sessions#setLocation'
  
  get '/users/profile' => 'users#show'
  get '/users/edit' => 'users#edit'
  patch '/users/edit' => 'users#update'  
  delete '/users' => 'users#delete'
  resources :users

  get "/authorities/login" => 'authorities#login'
  post "/authorities/login" => 'authorities#check_login'
  get "/authorities/profile" => 'authorities#show'
  get "/authorities/edit" => 'authorities#edit'
  patch "/authorities/edit" => 'authorities#update'
  delete '/authorities/sign_out' => 'authorities#destroy'

  get "admin/login" => 'admins#new'
  post "admin/login" => 'admins#create'
  get "admin" => 'admins#index'
  delete '/admin/sign_out' => 'admins#destroy'
  get "admin/create_authority" => 'authorities#new'
  post "admin/create_authority" => 'authorities#create'
  get "admin/list_authorities" => 'authorities#list'
  get "admin/list_users" => 'admins#list_users'
  get "admin/edit_user" => 'admins#edit_user'
  patch "admin/edit_user" => 'admins#update_user'
end

app/views/admins/edit_user.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <h1 class="title"> Edit User </h1>

        <% if @user.errors.any? %>
        <div id="error_explanation">            
            <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <%= form_with model: @user, url: '/admin/edit_user' do |form| %>
            <div class="field">
                <%= form.hidden_field :id %>
            </div>
            <div class="field">
                <%= form.label :username %>
                <%= form.text_field :username %>
            </div>
            <div class="field">
                <%= form.label :email %>
                <%= form.email_field :email %>
            </div>
            <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name %>
            </div>
            <div class="field">
                <%= form.label :birth_date, "Birth Date" %>
                <%= form.date_field :birth_date %>
            </div>
            <div class="buttons-container">
                <%= form.submit 'Save', class:"button" %>
            </div>
        <% end %>
        <div class="buttons-container">
            <%= link_to "Back", :back, class: 'button' %>
        </div>
    </div>
    <div class="sidebar"></div>
</div>

app/views/admins/index.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <h1 class="title"> Admin Management </h1>
        <div class="buttons-container">
            <%= link_to "List Users", '/admin/list_users', class: 'button' %>
            <%= link_to "List Authorities", '/admin/list_authorities', class: 'button' %>
            <%= link_to "Create Authority", '/admin/create_authority', class: 'button' %>
        </div>
        <div class="buttons-container">
            <%= link_to "Log out", '/admin/sign_out', method: :delete, class: 'button' %>
        </div>
    </div>
    <div class="sidebar"></div>
</div>

app/views/admins/list_users.html.erb
<%= javascript_include_tag "marker_list" %>
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">

    <p id="notice"><%= notice %></p>

    <h1 class="title">Users</h1>

    <div class="overflow-container" id="users">
      <table class="sortable">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Name</th>
            <th>Birth Date</th>
            <th>Created At</th>    
            <th colspan="3"> Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= user.name %></td>
              <td><%= user.birth_date.strftime("%d/%m/%Y") %></td>
              <td><%= user.created_at.strftime("%d/%m/%Y") %></td>
              <td><%= link_to 'Edit', admin_edit_user_path(@user, user: user) %></td>
              <td><%= link_to 'Destroy', users_path(@user, user: user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>    
    </div>
    <div class="buttons-container">
      <%= link_to "Back", '/admin', class: 'button' %>
    </div>
  </div>
<div class="sidebar"></div>
</div>

app/views/admins/new.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <img class="logo" src="/logo.png" alt="EnvSignal"/>
        <h1 class="title">Admin</h1>

        <% flash.each do |type, msg| %>
            <div id="error_explanation">    
                <%= msg %>
            </div>
            <% end %>
        <% flash.clear %>
        <%= form_with url: admin_login_path do |form| %>
            <div class="field">
                <%= form.label :username %>
                <%= form.text_field :username, placeholder: "write your username..."  %>
            </div>
            <div class="field">
                <%= form.label :password %>
                <%= form.password_field :password, placeholder: "write your password..."  %>
            </div>
            <div class="buttons-container">
                <%= form.submit 'Login', class:"button"%>
            </div>
        <% end %>
    </div>
    <div class="sidebar"></div>
</div>