config/routes.rb
Rails.application.routes.draw do
  get '/markers/self' => "markers#self"
  resources :markers
  get '/markers/:id/up' => "markers#upvote"
  get '/markers/:id/down' => "markers#downvote"
  get '/markers/:id/verify' => "markers#verify"
  get '/markers/:id/resolve' => "markers#resolve"
  

  root to: 'homes#index'
  get "homes" => "homes#index"
  get "user" => "homes#user"
  get "authority" => "homes#authority"
  get "login" => "homes#login"

  get    '/users/login'   => 'sessions#new'
  post   '/users/login'   => 'sessions#create'
  delete '/users/sign_out'  => 'sessions#destroy'
  get "setLocation" => 'sessions#setLocation'
  
  get '/users/profile' => 'users#show'
  get '/users/edit' => 'users#edit'
  patch '/users/edit' => 'users#update'  
  delete '/users' => 'users#delete'
  resources :users

  get "/authorities/login" => 'authorities#login'
  post "/authorities/login" => 'authorities#check_login'
  get "/authorities/profile" => 'authorities#show'
  get "/authorities/edit" => 'authorities#edit'
  patch "/authorities/edit" => 'authorities#update'
  delete '/authorities/sign_out' => 'authorities#destroy'

  get "admin/login" => 'admins#new'
  post "admin/login" => 'admins#create'
  get "admin" => 'admins#index'
  delete '/admin/sign_out' => 'admins#destroy'
  get "admin/create_authority" => 'authorities#new'
  post "admin/create_authority" => 'authorities#create'
  get "admin/list_authorities" => 'authorities#list'
  get "admin/list_users" => 'admins#list_users'
  get "admin/edit_user" => 'admins#edit_user'
  patch "admin/edit_user" => 'admins#update_user'
end

app/models/marker.rb
class Marker < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :authority, optional: true

    validates :disaster_type, presence: {message: "You need to enter the disaster's type!"}
    validates :latitude, presence: {message: "You need to enter the latitude!"}
    validates :longitude, presence: {message: "You need to enter the longitude!"}
    validates :severity, absence: {message: "The marker is not verified!"}, unless: -> { verified? }
    validates :user_type, presence: {message: "Marker with no user_type!"}

    validate :checkAuthor

    def checkAuthor()
        if (self.user_id == nil)
            errors.add(:user_id, 'You need a valid creator!')
        elsif (self.user_type == 'userType')
            @res = User.find_by(id: self.user_id)
            if (@res == nil)
                errors.add(:user_id, 'You need a valid creator!')
            end
        elsif (self.user_type == 'authorityType')
            @res = Authority.find_by(id: self.user_id)
            if (@res == nil)
                errors.add(:user_id, 'You need a valid creator!')
            end
        end
    end

    def upvotes
        Voter.where(marker_id: self.id, vote: :upvote).length()
    end

    def downvotes
        Voter.where(marker_id: self.id, vote: :downvote).length()
    end

    enum severity: {I: 1, II: 2, III: 3, IV: 4}

    scope :own_user, -> (userId, userType) { where('user_id = ? AND user_type = ? AND resolved = ?',userId, userType, false) }
    scope :own_user_verified, -> (userId, userType) { where('verified = ? AND user_id = ? AND user_type = ? AND resolved = ?', true, userId, userType, false) }
    scope :own_user_pending, -> (userId, userType) { where('verified != ? AND user_id = ? AND user_type = ? AND resolved = ?', true, userId, userType, false) }
    scope :pending_marker, -> (userId, userType) { where('verified != ? AND ((user_id = ? AND user_type != ?) OR user_id != ?) AND resolved = ?', true, userId, userType, userId, false)}
    scope :verified_marker, -> (userId, userType) { where('verified = ? AND ((user_id = ? AND user_type != ?) OR user_id != ?) AND resolved = ?', true, userId, userType, userId, false)}

    scope :pending_marker_nouser, -> () { where('verified != ? AND resolved = ?', true, false)  }
    scope :verified_marker_nouser, -> () { where('verified = ? AND resolved = ?', true, false) }

    enum user_type: {userType: 0, authorityType: 1}
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update upvote downvote destroy verify resolve]
  before_action :authorize
  
  # GET /markers or /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # GET /markers/self
  def self
    @user = User.find_by(id: session[:user_id])

    if(@user != nil)
      @name = @user.name
      @markers = Marker.own_user(session[:user_id], 0)
    end
    @authority = Authority.find_by(id: session[:authority_id])
    if(@authority != nil)
      @name = @authority.name
      @markers = Marker.own_user(session[:authority_id], 1)
    end
    return render 'markers-self'
  end

  # POST /markers or /markers.json
  def create
    @userId = session[:user_id]
    @authorityId = session[:authority_id]

    if @userId
      newParams = marker_params.merge!(:user_id => @userId, :verified => false, :user_type => 0)
    elsif 
      newParams = marker_params.merge!(:user_id => @authorityId, :verified => true, :user_type => 1)
    end
    puts newParams
    @marker = Marker.new(newParams)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: "Marker was successfully created." }
        format.json { render :show, status: :created, location: @marker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    respond_to do |format|
      if (params[:marker][:severity])
        params[:marker][:severity] = params[:marker][:severity].to_i
      end
      if @marker.update(marker_edit_params)
        format.html { redirect_to @marker, notice: "Marker was successfully updated." }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @voter ||= Voter.find_by(user_id: current_user.id, marker_id: @marker.id)
    if @voter
      if @voter.upvote?
        @voter.destroy
        redirect_to @marker, notice: "Upvote removed"
      else
        @voter.upvote!
        redirect_to @marker, notice: "Upvoted succesfully (de-downvoted)"
      end
    else
      if Voter.new(user_id: current_user.id, marker_id: @marker.id, vote: :upvote).save
        redirect_to @marker, notice: "Upvoted succesfully"
      else
        redirect_to @marker, alert: "Failed to vote"
      end
    end
  end

  def downvote
    @voter ||= Voter.find_by(user_id: current_user.id, marker_id: @marker.id)
    if @voter
      if @voter.downvote?
        @voter.destroy
        redirect_to @marker, notice: "Downvote removed"
      else
        @voter.downvote!
        redirect_to @marker, notice: "Downvoted succesfully (de-upvoted)"
      end
    else
      if Voter.new(user_id: current_user.id, marker_id: @marker.id, vote: :downvote).save
        redirect_to @marker, notice: "Downvoted succesfully"
      else
        redirect_to @marker, alert: "Failed to vote"
      end
    end
  end

  def verify
    if authority_logged_in?
      if @marker.update(verified: true) 
        redirect_to @marker, notice: "Verified succesfully"
      else
        redirect_to @marker, alert: "Failed to verify"
      end
    end
  end

  def resolve
    if authority_logged_in?
      if @marker.update(resolved: true) 
        redirect_to @marker, notice: "Resolved succesfully"
      else
        redirect_to @marker, alert: "Failed to resolve"
      end
    end
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
        @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:markers).permit(:disaster_type, :latitude, :longitude, :obs, :verified, :severity)
    end

    def marker_edit_params
      params.require(:marker).permit(:disaster_type, :latitude, :longitude, :obs, :verified, :severity)
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
    include Math

    def calculateDistance (lat1, lon1, lat2, lon2)
        @lat1 = lat1.to_f
        @lat2 = lat2.to_f
        @lon1 = lon1.to_f
        @lon2 = lon2.to_f
        @o1 = @lat1 * Math::PI/180
        @o2 = @lat2 * Math::PI/180
        @dlat = (@lat2-@lat1) * Math::PI/180
        @dlon = (@lon2-@lon1) * Math::PI/180
        @R = 6371e3
        @a = Math::sin(@dlat/2) * Math::sin(@dlat/2) + Math::cos(@o1) * Math::cos(@o2) * Math::sin(@dlon/2) * Math::sin(@dlon/2)
        @c = 2 * Math::atan2(Math::sqrt(@a), Math::sqrt(1-@a))
        @d = (@c * @R)/1000
        @dist = @d.round(2)
        return @dist
    end
end

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= form_with model: @marker, url: marker_url(@marker), method: :patch do |form| %>
    <% if @marker.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

            <ul>
                <% @marker.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :disaster_type %>
        <%= form.select :disaster_type, [["Water leak", "leak"], 
                                    ["Fire", "fire"], 
                                    ["Irregular Sewage Dump","sewage"], 
                                    ["Irregular Garbage Dump","garbage"]] %>
    </p>

    <p>
        <%= form.label :latitude %>
        <%= form.text_field :latitude %>
    </p>
                                
    <p>
        <%= form.label :longitude %>
        <%= form.text_field :longitude %>
    </p>
                                
    <p>
        <%= form.label :obs %>
        <%= form.text_field :obs %>
    </p>

    <% if session[:authority_id] %>
        <p>
            <%= form.label :verified %>
            <%= form.check_box :verified %>
        </p>

        <p>
            <%= form.label :severity %>
            <%= form.select :severity, [["I",1],["II",2],["III",3],["IV",4]] %>
        </p>
    <% end %>

    <p>
        <%= form.submit 'Save' %>
    </p>
<% end %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', root_path, method: 'get' %>

app/views/markers/index.html.erb
<%= javascript_include_tag "marker_list" %>
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">

    <p id="notice"><%= notice %></p>

    <h1 class="title">Markers</h1>

    <div id="coord_indication">
      <% if session[:latitude] == -23.4823919 && session[:longitude] == -46.5004498 %>
        <h2>
          EACH location being used 
        </h2>
      <% else %>
        <h2>
          Personal location being used
        </h2>
      <% end %>
    </div>
    <div class="overflow-container" id="disasters">
      <table class="sortable">
        <thead>
          <tr>
            <th>Type</th>
            <th>Severity</th>
            <th>Verified</th>
            <th>Observation</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Distance</th>
            <th>ID</th>
            <th>Creator</th>           
            <th>Upvotes</th>
            <th>Downvotes</th>            
            <th colspan="3"> Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @markers.each do |marker| %>
            <tr>
              <td><%= marker.disaster_type %></td>
              <td><%= marker.severity %> </td>
              <td><%= marker.verified %></td>
              <td><%= marker.obs %></td>
              <td><%= marker.latitude %></td>
              <td><%= marker.longitude %></td>
              <td><%= calculateDistance(marker.latitude, marker.longitude, session[:latitude], session[:longitude]) %> Km</td>
              <td><%= marker.user_id %></td> 
              <% if marker.user_type == "userType" %>
                <td>User</td>
              <% else %>
                <td>Auth</td>
              <% end %>
              <td><%= marker.upvotes %></td>
              <td><%= marker.downvotes %></td>
              <td><%= link_to 'Show', marker %></td>
              <% if session[:authority_id] or (session[:user_id] && session[:user_id] == marker.user_id) %>
                <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
                <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
                <td></td>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>    
    </div>
    <div class="buttons-container">
      <%= link_to 'New Marker', new_marker_path, class:"button" %>
      <%= link_to 'Back to Map', '/', class:"button" %>
    </div>
  </div>
<div class="sidebar"></div>
</div>

app/views/markers/markers-self.html.erb
<%= javascript_include_tag "marker_list" %>
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">

    <p id="notice"><%= notice %></p>

    <h1 class="title">Markers from <%= @name %></h1>

    <div id="coord_indication">
      <% if session[:latitude] == -23.4823919 && session[:longitude] == -46.5004498 %>
        <h2>
          EACH location being used 
        </h2>
      <% else %>
        <h2>
          Personal location being used
        </h2>
      <% end %>
    </div>
    <div class="overflow-container" id="disasters">
      <table class="sortable">
        <thead>
          <tr>
            <th>Type</th>
            <th>Severity</th>
            <th>Verified</th>
            <th>Obs</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Distance</th>
            <th>User</th>           
            <th>Upvotes</th>
            <th>Downvotes</th>            
            <th colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @markers.each do |marker| %>
            <tr>
            <td><%= marker.disaster_type %></td>
            <td><%= marker.severity %> </td>
            <td><%= marker.verified %></td>
            <td><%= marker.obs %></td>
            <td><%= marker.latitude %></td>
            <td><%= marker.longitude %></td>
            <td><%= calculateDistance(marker.latitude, marker.longitude, session[:latitude], session[:longitude]) %> Km</td>
            <td><%= marker.user_id %></td>              
            <td><%= marker.upvotes %></td>
            <td><%= marker.downvotes %></td>
            <td><%= link_to 'Show', marker %></td>
            <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
            <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>    
    </div>
    <div class="buttons-container">
      <%= link_to 'New Marker', new_marker_path, class:"button" %>
      <%= link_to 'Back to Map', '/', class:"button" %>
    </div>
  </div>
<div class="sidebar"></div>
</div>

app/views/markers/markers.html.erb
<div id="map"></div>
<% provide :head_tags do %>
<% end %>

app/views/markers/new.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">

      <% if @marker.errors.any? %>
      <div id="error_explanation">
        <h2>
          <% @marker.errors.count%> erro(s) impedindo o cadastro
        </h2>
        
        <ul>
            <% @marker.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
      </div>
        <% end %>

        <%= form_with scope: :markers, url: markers_path, local: true do |form| %>
        <h1 class="title">New Marker</h1>
        <div class="field">
          <%= form.label :disaster_type %>
          <%= form.select :disaster_type, 
          [["Water leak", "leak"], 
          ["Fire", "fire"], 
          ["Irregular Sewage Dump","sewage"], 
          ["Irregular Garbage Dump","garbage"]] %>
        </div>
          <div class="field">
            <%= form.label :latitude %>
            <%= form.text_field :latitude, placeholder: "write your latitude..." %>
          </div>

          <div class="field">
            <%= form.label :longitude %>
            <%= form.text_field :longitude, placeholder: "write your longitude..." %>
          </div>

          <div class="field">
            <%= form.label :obs %>
            <%= form.text_field :obs, placeholder: "write your observations..." %>
          </div>

          <div class="buttons-container">
              <%= form.submit 'Create', class: "button"%>
          </div>
        <% end %>

        <div class="buttons-container">
        <%= link_to 'Back', root_path, method: 'get', class: "button" %>
        </div>
      </div>
    <div class="sidebar"></div>
  </div>
<%= javascript_include_tag "markers" %>

app/views/markers/show.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
    <h1 class="title">View Marker</h1>

    <p id="notice"><%= notice %></p>
    
    <h3>
      <strong>Disaster_type:</strong>   <%= @marker.disaster_type %>
    </h3>

    <h3>
      <strong>Latitude:</strong>    <%= @marker.latitude %>
    </h3>

    <h3>
      <strong>Longitude:</strong>   <%= @marker.longitude %>
    </h3>

    <h3>
      <strong>Obs:</strong>   <%= @marker.obs %>
    </h3>

    <h3>
      <strong>User:</strong>    <%= @marker.user_id %>
    </h3>

    <h3>
      <strong>Upvotes:</strong>   <%= @marker.upvotes %>
    </h3>

    <h3>
      <strong>Downvotes:</strong>   <%= @marker.downvotes %>
    </h3>

    <h3>
      <strong>Verified:</strong>    <%= @marker.verified %>
    </h3>

    <h3>
      <strong>Severity:</strong>    <%= @marker.severity %>
    </h3>

    <h3>
      <strong>Solved:</strong>    <%= @marker.resolved %>
    </h3>

    <div class="buttons-container">
    <% if session[:authority_id] %>
      <%= link_to 'Verify', '/markers/' + @marker.id.to_s + '/verify', class:"button" %>
      <%= link_to 'Remove', '/markers/' + @marker.id.to_s, method: 'delete', class:"button" %>
      <% if @marker.verified? %>
        <%= link_to 'Resolve', '/markers/' + @marker.id.to_s + '/resolve', class:"button" %>
      <% end %>
    <% end %>
    <% if @marker.user_id == session[:user_id] or session[:authority_id] %>
      <%= link_to 'Edit', edit_marker_path(@marker), class: "button" %> 
    <% else %>
      <%= link_to '/markers/' + @marker.id.to_s + '/up', class:"button" do %>
        Upvote<img src="/thumb-up.png" alt="Upvote">
      <% end %> 
      <%= link_to '/markers/' + @marker.id.to_s + '/down', class:"button" do %>
        Downvote<img src="/thumb-down.png" alt="Downvote">
      <% end %> 
    <% end %>
    </div>
    <div class="buttons-container">
      <%= link_to 'Back', root_path, method: 'get', class:"button" %>
    </div>
  </div>
  <div class="sidebar"></div>
</div>