config/routes.rb
Rails.application.routes.draw do
  get '/markers/self' => "markers#self"
  resources :markers
  get '/markers/:id/up' => "markers#upvote"
  get '/markers/:id/down' => "markers#downvote"
  get '/markers/:id/verify' => "markers#verify"
  get '/markers/:id/resolve' => "markers#resolve"
  

  root to: 'homes#index'
  get "homes" => "homes#index"
  get "user" => "homes#user"
  get "authority" => "homes#authority"
  get "login" => "homes#login"

  get    '/users/login'   => 'sessions#new'
  post   '/users/login'   => 'sessions#create'
  delete '/users/sign_out'  => 'sessions#destroy'
  get "setLocation" => 'sessions#setLocation'
  
  get '/users/profile' => 'users#show'
  get '/users/edit' => 'users#edit'
  patch '/users/edit' => 'users#update'  
  delete '/users' => 'users#delete'
  resources :users

  get "/authorities/login" => 'authorities#login'
  post "/authorities/login" => 'authorities#check_login'
  get "/authorities/profile" => 'authorities#show'
  get "/authorities/edit" => 'authorities#edit'
  patch "/authorities/edit" => 'authorities#update'
  delete '/authorities/sign_out' => 'authorities#destroy'

  get "admin/login" => 'admins#new'
  post "admin/login" => 'admins#create'
  get "admin" => 'admins#index'
  delete '/admin/sign_out' => 'admins#destroy'
  get "admin/create_authority" => 'authorities#new'
  post "admin/create_authority" => 'authorities#create'
  get "admin/list_authorities" => 'authorities#list'
  get "admin/list_users" => 'admins#list_users'
  get "admin/edit_user" => 'admins#edit_user'
  patch "admin/edit_user" => 'admins#update_user'
end

app/models/authority.rb
class Authority < ApplicationRecord

    has_secure_password validations: false
    validates :name, presence: {message: "You need to enter your name!"}
    validates :identifier, presence: {message: "You need to enter your identifier!"}, uniqueness: {message: 'Identifier not available!'}
    validates :password, presence: {message: "You need to enter your password!"}, on: :create
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
    before_action :authority_block_access, except: [:destroy, :show, :edit, :update]
    before_action :authority_authorize, except: [:new, :create, :list, :login, :check_login]
    before_action :admin_authorize, only: [:new, :create, :list]
    before_action :validate_authority_login, only: [:login, :check_login, :show]

    def new
        @authority = Authority.new
    end

    def create
        @authority = Authority.new(authorities_params)
        if @authority.save
            respond_to do |format|
                format.html { redirect_to controller: 'authorities', action: 'list'}
            end
        else
            render 'new'
        end
    end

    def show
        @authority = Authority.find_by(id: session[:authority_id])
    end

    def login
    end

    def check_login
        if params[:identifier] == '' or params[:password] == '' or !params[:identifier] or !params[:password]
            flash.alert = 'Identifier or Password not entered'
            redirect_to '/authorities/login'
        else
            @authority = Authority.find_by(identifier: params[:identifier])
            if @authority.present? && @authority.authenticate(params[:password])
                session[:authority_id] = @authority.id
                redirect_to "/authority"
            else
                flash.alert = 'Incorrect identifier or password'
                redirect_to '/authorities/login'
            end
        end
    end

    def destroy
        authority_sign_out
        redirect_to '/authorities/login'
    end

    def list
        @authorities = Authority.select(:identifier, :name)
    end

    def edit
        @authority = Authority.find_by(id: session[:authority_id])
    end
    
    def update
        @authority = Authority.find_by(id: session[:authority_id])
        if @authority.update(edit_params)
            flash.alert = 'Profile updated!'
            redirect_to '/authorities/profile'
        else
            render action: :edit
        end
    end

    def authority_sign_out
        session.delete(:authority_id)
        @current_authority = nil
    end

    def authority_block_access
        if authority_logged_in?
            redirect_to '/authority'
        end
    end

    def validate_authority_login
        if logged_in?
            redirect_to '/users/profile'
        end
    end


    private
    def authorities_params
        params.require(:authorities).permit(:identifier, :name, :password)
    end

    private
    def edit_params
        params.require(:authority).permit(:identifier, :name)
    end

end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/edit.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <h1 class="title"> Edit Authority Data</h1>

        <% if @authority.errors.any? %>
        <div id="error_explanation">    
            <ul>
                <% @authority.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <%= form_with model: @authority, url: '/authorities/edit' do |form| %>
            <div class="field">
                <%= form.label :identifier %><br />
                <%= form.text_field :identifier %>
            </div>
            <div class="field">
                <%= form.label :name %><br />
                <%= form.text_field :name %>
            </div>
            <div class="buttons-container">
                <%= form.submit 'Save', class:"button" %>
            </div>
        <% end %>
        <div class="buttons-container">
            <%= link_to 'Back', :back, class:"button" %>
        </div>
    </div>
    <div class="sidebar"></div>
</div>

app/views/authorities/list.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
    <h1 class="title"> Authorities Management Page</h1>

    <table>
      <tr>
        <th>Identifier</th>
        <th>Name</th>
      </tr>
      <% @authorities.each do |aut| %>
        <tr>
            <td><%= aut.identifier%></td>
            <td><%= aut.name%></td>
        </tr>
        <%end%>
    </table>

    <div class="buttons-container">
      <%= link_to "Register New Authority", '/admin/create_authority', class:"button" %>
    </div>
    <div class="buttons-container">
      <%= link_to "Back", '/admin', class:"button" %>
    </div>
  </div>
  <div class="sidebar"></div>
</div>

app/views/authorities/list_disasters.html.erb
<%= javascript_include_tag "auth_list" %>

<h1>Disaster List</h1>

<div id="coord_indication">
  <% if session[:latitude] == -23.4823919 && session[:longitude] == -46.5004498 %>
    <h2>
        Localização da EACH sendo utilizada
    </h2>
  <% else %>
    <h2>
      Localização pessoal sendo utilizada
    </h2>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Verified</th>
      <th>Type</th>
      <th>Obs</th>
      <th>User</th>
      <th>Distance</th>
      <th>Upvotes</th>
      <th>Downvotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= marker.verified %></td>
        <td><%= marker.disaster_type %></td>
        <td><%= marker.obs %></td>
        <td><%= marker.user_id %></td>
        <td><%= calculateDistance(marker.latitude, marker.longitude, session[:latitude], session[:longitude]) %> Km</td>
        <td><%= marker.upvotes %></td>
        <td><%= marker.downvotes %></td>
        <td><%= link_to 'Show', marker %></td>
        <td><%= link_to 'Edit', edit_marker_path(marker) %></td>
        <td><%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authorities/login.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <img class="logo" src="/logo.png" alt="EnvSignal"/>
        <h1 class="title">Authority</h1>
            <% flash.each do |type, msg| %>
                <div id="error_explanation">    
                    <%= msg %>
                </div>
                <% end %>
            <% flash.clear %>
            <%= form_with url: authorities_login_path do |form| %>
                <div class="field">
                    <%= form.label :identifier %>
                    <%= form.text_field :identifier, placeholder: "write your identifier..."  %>
                </div>
                <div class="field">
                    <%= form.label :password %>
                    <%= form.password_field :password, placeholder: "write your password..."  %>
                </div>
                <div class="buttons-container">
                    <%= form.submit 'Login', class:"button"%>
                </div>
                <span>or <%= link_to "sign in as user", "/users/login", class: "user_login_link"%></span>
        <% end %>
    </div>
    <div class="sidebar"></div>
    </div>

app/views/authorities/new.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <h1 class="title">Register Authority</h1>

        <% if @authority.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% @authority.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <%= form_with scope: :authorities, local: true do |form| %>
            <div class="field">
                <%= form.label :identifier %>
                <%= form.text_field :identifier, placeholder: "write the identifier..."%>
            </div>
            <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name, placeholder: "write the name..." %>
            </div>
            <div class="field">
                <%= form.label :password %>
                <%= form.password_field :password, placeholder: "write the password..." %>
            </div>
            <div class="buttons-container">
                <%= form.submit 'Create', class:"button"%>
            </div>
        <% end %>
        <div class="buttons-container">
            <%= link_to "Back", :back, class: 'button' %>
        </div>
    </div>
    <div class="sidebar"></div>
</div>

app/views/authorities/show.html.erb
<div class="default-container">
    <div class="sidebar"></div>
    <div class="hero">
        <h1 class="title"> Authority Page</h1>

        <% flash.each do |type, msg| %>
            <div id="success_explanation">    
                <%= msg %>
            </div>
        <% end %>
        <% flash.clear %>
        <h3><strong><%= @authority.name %>'s Profile </strong></h3>
        <h3><strong>Identifier:</strong> <%= @authority.identifier %> </h3>
        <h3><strong>Username:</strong> <%= @authority.name %> </h3>
        <div class="buttons-container">
            <%= link_to 'Back to Map', '/', class:"button" %>
            <%= link_to "Edit Authority Profile", '/authorities/edit', class:"button" %>
            <%= link_to "Log out", '/authorities/sign_out', method: :delete, class:"button" %>
        </div>
    </div>
    <div class="sidebar"></div>
</div>